In [13]:
import numpy as np

In [2]:
import pandas as pd

In [6]:
dataset=pd.read_csv('G:\Courses\Advance programming Languages\MultiLinearRegression.csv')

In [7]:
x=dataset.iloc[:,:-1].values

In [8]:
y=dataset.iloc[:,3].values

In [9]:
from sklearn.model_selection import train_test_split
x_train, x_testimport numpy as py, y_train,y_test=train_test_split(x,y,test_size=0.3, random_state=0)

In [11]:
from sklearn.linear_model import LinearRegression
reg=LinearRegression()
reg.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [12]:
y_pridict=reg.predict(x_test)

In [15]:
print(y_pridict)
      

[170776.24586317 154453.75527336 181711.01912432 134820.99356286]


In [16]:
x

array([[165349.2 , 136897.8 , 471784.1 ],
       [162597.7 , 151377.6 , 443898.5 ],
       [153441.5 , 101145.6 , 407934.5 ],
       [144372.4 , 118671.9 , 383199.6 ],
       [142107.3 ,  91391.77, 366168.4 ],
       [131876.9 ,   9981.71, 362861.4 ],
       [134615.5 , 147198.9 , 127716.8 ],
       [130298.1 , 145530.1 ,  32386.7 ],
       [120542.5 , 148719.  , 311613.3 ],
       [123334.9 , 108679.2 , 304981.6 ],
       [101913.1 , 110594.1 , 229161.  ]])

In [17]:
y

array([192261.8, 191792.1, 191050.4, 182902. , 166187.9, 156991.1,
       156122.5, 155752.6, 152211.8, 149760. , 146122. ])